### ISSUE TITLE
Unexpected token export grocery.model.js

### ISSUE THREAD

**Issue by mokhosh** [NativeScript/playground-feedback#30] opened 2018-05-05 21:23 UTC
### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
No, sorry

### Tell us about the problem
I'm stuck in level 14, the app doesn't compile

### Did you try it outside of {N} Playground?
No

### Which browser are you using?
Mozilla

### Are there any errors/warnings logged in your browser console?
No

### Which platform(s) does your issue occur on?
Android

### Are there any entries logged in the Device Logs tab?
unexpected token export, with a long stack trace

### Please provide the following information shown in devices tab in the playground:

- Nexus 5X 
- Android 8.1.0 
- 1.11.0 
- 4.0.1

### Please tell us how to recreate the issue with as much detail as possible.
do the playground up to level 14

```
[Nexus 5X]: com.tns.NativeScriptException:

Error calling module function

Error calling module function

Error calling module function

Error calling module function

Error calling module function

Cannot compile /data/data/org.nativescript.preview/files/app/shared/grocery/grocery.model.js

SyntaxError: Unexpected token export
File: "file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.model.js, line: 1, column: 60

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token export
File: ", line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token export
File: ", line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token export
File: ", line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token export
File: ", line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token export
File: ", line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected token export
File: ", line: 1, column: 265

StackTrace:
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/shared/grocery/grocery.service.js', line: 10, column: 25
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/list/list.component.js', line: 4, column: 27
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.routing.js', line: 4, column: 26
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.module.js', line: 10, column: 23
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/main.js', line: 5, column: 20
Frame: function:'require', file:'', line: 1, column: 266


at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:530)
at com.tns.Runtime.run(Runtime.java:522)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by vhristov5555** [comment] 2018-05-06 08:39
Hi,
Sorry for the unconvinced caused.

Could please send us a saved session with the problem you have faced?

I have complete successfully step 14. This is the saved session with completed step 14 - https://play.nativescript.org/?template=groceries-ng&tutorial=groceries-ng&id=Gr7fKl
Could you please try to scan the saved session and verify if it is working on your side?

**Comment by mokhosh** [comment] 2018-05-07 12:51
Thanks for your response.

Unfortunately I have closed the session.
Your saved session did work, even though we both have the exact same grocery.model.ts file.

**Comment by vhristov5555** [comment] 2018-05-08 07:29
Thanks for the feedback.

Unfortunetly we were unable to reproduce the problem.
I will close the issue.
If you find steps to reproduce or have furhter questions please don't haste to write to us.

**Closed by vhristov5555** 2018-05-08 07:29 UTC
